### ISSUE TITLE
Plots.jl+pyplot() interacts badly with PNGFiles.jl

### ISSUE THREAD

**Issue by jaakkor2** [JuliaIO/PNGFiles.jl#24] opened 2020-09-25 14:39 UTC
```
using Plots
using FileIO
pyplot() # remove this line and the example works fine
FileIO.load("DSC_999.png")
```
gives me
```
Errors encountered while loading "C:\\Users\\jaakkor2\\Work\\Julia\\DSC_999.png".
All errors:
===========================================
ReadOnlyMemoryError()
===========================================
ArgumentError: Package ImageMagick not found in current path:
- Run `import Pkg; Pkg.add("ImageMagick")` to install the ImageMagick package.

===========================================

Fatal error:
ERROR: ReadOnlyMemoryError()
Stacktrace:
 [1] handle_error(::ReadOnlyMemoryError, ::File{DataFormat{:PNG}}) at C:\Users\jaakkor2\.julia\packages\FileIO\wN5rD\src\error_handling.jl:82
 [2] handle_exceptions(::Array{Any,1}, ::String) at C:\Users\jaakkor2\.julia\packages\FileIO\wN5rD\src\error_handling.jl:77
 [3] load(::FileIO.Formatted; options::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\Users\jaakkor2\.julia\packages\FileIO\wN5rD\src\loadsave.jl:207
 [4] load at C:\Users\jaakkor2\.julia\packages\FileIO\wN5rD\src\loadsave.jl:184 [inlined]
 [5] #load#14 at C:\Users\jaakkor2\.julia\packages\FileIO\wN5rD\src\loadsave.jl:133 [inlined]
 [6] load(::String) at C:\Users\jaakkor2\.julia\packages\FileIO\wN5rD\src\loadsave.jl:133
 [7] top-level scope at REPL[4]:1
```
I do not have ImageMagick.jl installed, but I do have
. Plots.jl v1.6.6
. FileIO v1.4.3
. ImageIO.jl v0.3.0
. PNGFiles v0.3.1

Without the call `pyplot()` the example works fine.

In issue https://github.com/JuliaIO/FileIO.jl/issues/275 it was guided to open an issue here.

**Comment by Drvi** [comment] 2020-09-26 13:27
Hmm, I can't reproduce the problem using a test image from Wikimedia, having the same versions of mentioned libs:
```julia
julia> using Plots, FileIO
julia> pyplot()
Plots.PyPlotBackend()

julia> FileIO.load(download("https://upload.wikimedia.org/wikipedia/commons/6/6a/PNG_Test.png"))
3920×3120 Array{RGB{N0f8},2} with eltype RGB{FixedPointNumbers.Normed{UInt8,8}}:
 RGB{N0f8}(0.0,0.0,0.0)  RGB{N0f8}(0.0,0.0,0.0)  …  RGB{N0f8}(0.09,0.443,0.906)
 RGB{N0f8}(0.0,0.0,0.0)  RGB{N0f8}(0.0,0.0,0.0)     RGB{N0f8}(0.725,0.796,1.0)
 RGB{N0f8}(0.0,0.0,0.0)  RGB{N0f8}(0.0,0.0,0.0)     RGB{N0f8}(0.725,0.796,1.0)
 RGB{N0f8}(0.0,0.0,0.0)  RGB{N0f8}(0.0,0.0,0.0)     RGB{N0f8}(0.725,0.796,1.0)
 RGB{N0f8}(0.0,0.0,0.0)  RGB{N0f8}(0.0,0.0,0.0)     RGB{N0f8}(0.725,0.796,1.0)
```
What version of julia are you using?


```
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PATH = /home/drvi/src/julia-1.5.0/bin
  JULIA_VERSION = 1.5.0
```

**Comment by jaakkor2** [comment] 2020-09-26 13:58
I too cannot reproduce this issue on Linux.  The issue arises on Windows
```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Program Files\Sublime Text 3\sublime_text.exe"
  JULIA_NUM_THREADS = 4
```

**Comment by ianshmean** [comment] 2020-09-26 14:37
Could you try directly using the PNGFiles loader? It should give a nicer stacktrace. 

```
using PNGFiles
PNGFiles.load("path")
```

**Comment by jaakkor2** [comment] 2020-09-26 14:43
This works directly
```
julia> using PNGFiles
julia> PNGFiles.load("DSC_999.png")
1024×768 Array{Gray{N0f8},2} with eltype ColorTypes.Gray{FixedPointNumbers.Normed{UInt8,8}}:
 Gray{N0f8}(0.471)  Gray{N0f8}(0.698)  Gray{N0f8}(0.059)  …  Gray{N0f8}(0.714)  Gray{N0f8}(0.435)  Gray{N0f8}(0.565)
 Gray{N0f8}(0.612)  Gray{N0f8}(0.792)  Gray{N0f8}(0.118)     Gray{N0f8}(0.392)  Gray{N0f8}(0.8)    Gray{N0f8}(0.78)
...
```
and this as well
```
julia> using Plots
julia> using PNGFiles
julia> pyplot()
Plots.PyPlotBackend()
julia> PNGFiles.load("DSC_999.png")
1024×768 Array{Gray{N0f8},2} with eltype Gray{FixedPointNumbers.Normed{UInt8,8}}:
 Gray{N0f8}(0.471)  Gray{N0f8}(0.698)  Gray{N0f8}(0.059)  …  Gray{N0f8}(0.714)  Gray{N0f8}(0.435)  Gray{N0f8}(0.565)
 Gray{N0f8}(0.612)  Gray{N0f8}(0.792)  Gray{N0f8}(0.118)     Gray{N0f8}(0.392)  Gray{N0f8}(0.8)    Gray{N0f8}(0.78)
 Gray{N0f8}(0.0)    Gray{N0f8}(0.667)  Gray{N0f8}(0.71)      Gray{N0f8}(0.004)  Gray{N0f8}(0.125)  Gray{N0f8}(0.263)
 ...
```
I initially thought somehow FileIO gets confused, and I opened an issue there originally.

**Comment by ianshmean** [comment] 2020-09-26 14:48
How about ImageIO?

```
using ImageIO
using FileIO: File, DataFormat
ImageIO.load(File{DataFormat{:PNG}}("DSC_999.png"))
```

**Comment by jaakkor2** [comment] 2020-09-26 14:53
This works
```
julia> using ImageIO

julia> using FileIO: File, DataFormat

julia> ImageIO.load(File{DataFormat{:PNG}}("DSC_999.png"))
1024×768 Array{Gray{N0f8},2} with eltype ColorTypes.Gray{FixedPointNumbers.Normed{UInt8,8}}:
 Gray{N0f8}(0.471)  Gray{N0f8}(0.698)  Gray{N0f8}(0.059)  …  Gray{N0f8}(0.714)  Gray{N0f8}(0.435)  Gray{N0f8}(0.565)
 Gray{N0f8}(0.612)  Gray{N0f8}(0.792)  Gray{N0f8}(0.118)     Gray{N0f8}(0.392)  Gray{N0f8}(0.8)    Gray{N0f8}(0.78)
..
```
This does _not_ work
```
julia> using Plots

julia> using ImageIO

julia> using FileIO: File, DataFormat

julia> pyplot()
Plots.PyPlotBackend()

julia> ImageIO.load(File{DataFormat{:PNG}}("DSC_999.png"))
ERROR: ReadOnlyMemoryError()
Stacktrace:
 [1] png_read_info at C:\Users\jaakkor2\.julia\packages\PNGFiles\Sgsmw\gen\libpng\libpng_api.jl:96 [inlined]
 [2] _load(::Ptr{Nothing}, ::Ptr{Nothing}; gamma::Nothing, expand_paletted::Bool) at C:\Users\jaakkor2\.julia\packages\PNGFiles\Sgsmw\src\io.jl:59
 [3] load(::String; gamma::Nothing, expand_paletted::Bool) at C:\Users\jaakkor2\.julia\packages\PNGFiles\Sgsmw\src\io.jl:28
 [4] load(::String) at C:\Users\jaakkor2\.julia\packages\PNGFiles\Sgsmw\src\io.jl:23
 [5] #invokelatest#1 at .\essentials.jl:710 [inlined]
 [6] invokelatest(::Any, ::Any) at .\essentials.jl:709
 [7] load(::File{DataFormat{:PNG}}; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\Users\jaakkor2\.julia\packages\ImageIO\DOpZl\src\ImageIO.jl:13
 [8] load(::File{DataFormat{:PNG}}) at C:\Users\jaakkor2\.julia\packages\ImageIO\DOpZl\src\ImageIO.jl:9
 [9] top-level scope at REPL[6]:1
```

**Comment by ianshmean** [comment] 2020-09-26 15:10
ImageIO lazily loads PNGFiles, so my guess is that there's some lib clash between Plots/PyPlot & PNGFiles, and the load ordering matters on windows.. or something like that.

Does the same happen without loading the PyPlot backend?

**Comment by ianshmean** [comment] 2020-09-26 15:31
Thinking about load order, what about these:

```
using Plots
using ImageIO
using FileIO: File, DataFormat
using PNGFiles
pyplot()
ImageIO.load(File{DataFormat{:PNG}}("DSC_999.png"))
```

```
using PNGFiles
using Plots
using ImageIO
using FileIO: File, DataFormat
pyplot()
ImageIO.load(File{DataFormat{:PNG}}("DSC_999.png"))
```

**Comment by ianshmean** [comment] 2020-09-26 19:30
Ok, I can reproduce this in Windows with julia 1.5.2

Loading PNGFiles before switching to `pyplot()` "fixes" it.
```
julia> using Plots, FileIO

julia> using PNGFiles

julia> pyplot()
Plots.PyPlotBackend()

julia> FileIO.load(download("https://upload.wikimedia.org/wikipedia/commons/6/6a/PNG_Test.png"))
3920×3120 Array{RGB{N0f8},2} with eltype RGB{FixedPointNumbers.Normed{UInt8,8}}:
```

Both matplotlib and PNGFiles use the same version of libpnb, 1.6.37, but perhaps the python version has some other build settings that messes up our library usage
https://github.com/JuliaPackaging/Yggdrasil/blob/b0f35b382d770a7fa672b850623915aade5c24c2/L/libpng/build_tarballs.jl#L6

**Comment by ianshmean** [comment] 2020-09-26 21:25
Ok.. so after some manual testing, it seems that julia doesn't like using the libpng16 that PyPlots loads (maybe because it was compiled with msvc), and in <1.6 julia, the jll's load the dlls and provide just the dll name, so julia is grabbing the one that's loaded first, which happens to be the pyplot libpng16.

So before julia 1.6, the fix is to load PNGFiles before PyPlot.

In 1.6 jll's will link to libs at specific paths using the new jllwrappers mechanics, so this _should_ be fixed on 1.6

Thanks to @giordano for the help debugging this

**Comment by Drvi** [comment] 2020-09-26 21:33
Thats some impressive detective work, thanks @ianshmean @giordano !

**Comment by johnnychen94** [comment] 2021-03-12 01:35
I believe there's nothing that needs to be fixed in this package so I'll just close this one.

**Closed by johnnychen94** 2021-03-12 01:35 UTC
